module.exports = {
  COGNITO_APP_CLIENT_ID: process.env.COGNITO_APP_CLIENT_ID,
  COGNITO_APP_CLIENT_CALLBACK_URL: process.env.COGNITO_APP_CLIENT_CALLBACK_URL,
  COGNITO_DOMAIN: process.env.COGNITO_DOMAIN,z
}
